#!/usr/bin/env bash
# Incremental rebuild of _rocm_C via the cached cmake/ninja build dir.
# This is what the previous working build (w4a8_runs/build5.log) used:
# cmake has already configured build/temp.linux-x86_64-cpython-312, so a plain
# `ninja _rocm_C` recompiles only the changed TUs and relinks. Running
# `pip install -e .` instead re-configures from scratch and fails on the
# ROCm 7.14 non-standard SDK layout (/opt/rocm/core-7.14).
set -uo pipefail
T=${T:-/home/chenco_adm/vllm-rdna-0.28.0}
V=${V:-/home/chenco_adm/Apps/vllm/venv-7.14.0_0.28.0}
BD=$T/build/temp.linux-x86_64-cpython-312

ROCM_SDK_LIB="$V/lib/python3.12/site-packages/_rocm_sdk_libraries/lib"
ROCM_SDK="$V/lib/python3.12/site-packages/_rocm_sdk_core/lib"
export LD_LIBRARY_PATH="$ROCM_SDK_LIB:$ROCM_SDK/host-math/lib:$ROCM_SDK/rocm_sysdeps/lib:$ROCM_SDK/core/lib:$V/lib/python3.12/site-packages/torch/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PATH="$V/bin:/opt/rocm/core-7.14/bin:$PATH"
export CMAKE_HIP_COMPILER=/opt/rocm/core-7.14/lib/llvm/bin/clang++
# The 7.14 SDK keeps the AMDGPU device bitcode under lib/llvm/amdgcn/bitcode
# (not <rocm>/amdgcn/bitcode), so clang++ needs the override or every HIP
# compile dies with "cannot find ROCm device library".
export HIP_DEVICE_LIB_PATH=/opt/rocm/core-7.14/lib/llvm/amdgcn/bitcode
# NB: do NOT export HIP_CLANG_PATH here. cmake's link helper
# (hipcc_cmake_linker_helper) sets HIP_CLANG_PATH itself from the compiler dir
# baked into the link rule; an env value takes precedence in paths where the
# helper does not override it and makes hipcc exec "<env>/clang++" (a
# "Not a directory" failure).

# cmake's FindHIP hardcodes the standard <rocm>/llvm/bin compiler dir when it
# generates the HIP link rule, but this 7.14 SDK keeps LLVM under
# <rocm>/lib/llvm/bin, so the generated rule invokes a non-existent
# .../llvm/bin/clang++ and the link fails. Patch the generated rule (a build
# artifact, regenerated by cmake) to the real path.
RULES="$BD/CMakeFiles/rules.ninja"
if grep -q "/opt/rocm/core-7.14/llvm/bin" "$RULES" 2>/dev/null; then
  sed -i 's#/opt/rocm/core-7.14/llvm/bin#/opt/rocm/core-7.14/lib/llvm/bin#g' "$RULES"
  echo "[incr-build] patched HIP link rule -> lib/llvm/bin"
fi

cd "$BD"
echo "[incr-build] start $(date +%H:%M:%S)"
ninja _rocm_C
rc=$?
echo "[incr-build] ninja_rc=$rc $(date +%H:%M:%S)"
if [ "$rc" = "0" ]; then
  ls -la "$T/vllm/_rocm_C.abi3.so"
fi
exit $rc
